---
- name: Debug
  hosts: all
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  tasks:
    - name: Debug ansible_facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Debug hostvars
      ansible.builtin.debug:
        var: hostvars
