---
- name: Trim SSDs
  hosts: pies4
  become: true
  become_user: root
  tasks:
    - name: Ensure udev rule for usb ssd exists
      ansible.builtin.copy:
        src: ./files/10-trim.rules
        dest: /etc/udev/rules.d/10-trim.rules
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reboot

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
    - name: Trim
      ansible.builtin.command:
        cmd: fstrim -v --all
        strip_empty_ends: true
      register: trim_output
      changed_when: true

    - name: Display trim output
      ansible.builtin.debug:
        var: trim_output.stdout_lines # + trim_output.stderr_lines
      changed_when: false

    - name: Gather disk usage
      ansible.builtin.command:
        # cmd: duf -hide=special -hide-fs=squashfs -width 500
        # cmd: lsblk
        cmd: df --human-readable --print-type --exclude-type=tmpfs --exclude-type=squashfs --exclude-type=devtmpfs
      changed_when: true
      register: disk_usage_output

    - name: Display disk output
      ansible.builtin.debug:
        var: disk_usage_output.stdout_lines # + trim_output.stderr_lines
      changed_when: false

    - name: Ensure systemd fstrim timer is enabled
      ansible.builtin.systemd:
        name: fstrim.timer
        # state: started
        enabled: true
        daemon_reload: true

  handlers:
    - name: Reboot
      ansible.builtin.reboot:
        msg: "Reboot initiated"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
